export const INDIVIDUALS_LOADING = "INDIVIDUALS_LOADING";
export const ADD_INDIVIDUALS = "ADD_INDIVIDUALS";
export const INDIVIDUALS_FAILED = "INDIVIDUALS_FAILED";

export const ADD_COMMENTS = "ADD_COMMENTS";
export const COMMENTS_FAILED = "COMMENTS_FAILED";
